### ISSUE TITLE
Zookeeper KeeperErrorCode = NodeExists for /humio_3

### ISSUE THREAD

**Issue by estahn** [humio/issues#128]
Installing Humio (1.6.1) via humio-operator. I'm getting occasionally failing pods with this error message:

Using AWS MKS for Kafka.

```
{"commonElementCount":0,"localizedMessage":"KeeperErrorCode = NodeExists for /humio_3","message":"KeeperErrorCode = NodeExists for /humio_3","name":"org.apache.zookeeper.KeeperException$NodeExistsException","extendedStackTrace":"org.apache.zookeeper.KeeperException$NodeExistsException: KeeperErrorCode = NodeExists for /humio_3\n\tat org.apache.zookeeper.KeeperException.create(KeeperException.java:126) ~[humio-assembly.jar:0.1]\n\tat org.apache.zookeeper.KeeperException.create(KeeperException.java:54) ~[humio-assembly.jar:0.1]\n\tat org.apache.zookeeper.ZooKeeper.create(ZooKeeper.java:1538) ~[humio-assembly.jar:0.1]\n\tat com.humio.core.NodeIDUsingZookeeper.reacquirePath(NodeIDUsingZookeeper.scala:96) ~[humio-assembly.jar:0.1]\n\tat com.humio.core.NodeIDUsingZookeeper.atContextStart(NodeIDUsingZookeeper.scala:31) ~[humio-assembly.jar:0.1]\n\tat com.humio.core.Context.$anonfun$nodeUUIDFromZookeeper$1(Context.scala:359) ~[humio-assembly.jar:0.1]\n\tat scala.Option.map(Option.scala:242) ~[humio-assembly.jar:0.1]\n\tat com.humio.core.Context.<init>(Context.scala:359) ~[humio-assembly.jar:0.1]\n\tat com.humio.core.Context$.$anonfun$init$1(Context.scala:225) ~[humio-assembly.jar:0.1]\n\tat com.humio.util.Timing$.time(Timing.scala:16) ~[humio-assembly.jar:0.1]\n\tat com.humio.util.Timing$.time(Timing.scala:10) ~[humio-assembly.jar:0.1]\n\tat com.humio.core.Context$.init(Context.scala:221) ~[humio-assembly.jar:0.1]\n\tat com.humio.core.Context$.apply(Context.scala:185) ~[humio-assembly.jar:0.1]\n\tat com.humio.core.Context$.apply(Context.scala:167) ~[humio-assembly.jar:0.1]\n\tat com.humio.main.ServerRunner$.main(ServerRunner.scala:85) ~[humio-assembly.jar:0.1]\n\tat com.humio.main.ServerRunner.main(ServerRunner.scala) ~[humio-assembly.jar:0.1]\n"},"endOfBatch":true,"loggerFqcn":"org.apache.logging.log4j.spi.AbstractLogger","threadId":1,"threadPriority":5,"subtype":"humio"}
2020-10-26T03:50:16.309+0000 [main] ERROR c.h.m.ServerRunner$ - Got exception starting pid=1 org.apache.zookeeper.KeeperException$NodeExistsException: KeeperErrorCode = NodeExists for /humio_3
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:126) ~[humio-assembly.jar:0.1]
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:54) ~[humio-assembly.jar:0.1]
	at org.apache.zookeeper.ZooKeeper.create(ZooKeeper.java:1538) ~[humio-assembly.jar:0.1]
	at com.humio.core.NodeIDUsingZookeeper.reacquirePath(NodeIDUsingZookeeper.scala:96) ~[humio-assembly.jar:0.1]
	at com.humio.core.NodeIDUsingZookeeper.atContextStart(NodeIDUsingZookeeper.scala:31) ~[humio-assembly.jar:0.1]
	at com.humio.core.Context.$anonfun$nodeUUIDFromZookeeper$1(Context.scala:359) ~[humio-assembly.jar:0.1]
	at scala.Option.map(Option.scala:242) ~[humio-assembly.jar:0.1]
	at com.humio.core.Context.<init>(Context.scala:359) ~[humio-assembly.jar:0.1]
	at com.humio.core.Context$.$anonfun$init$1(Context.scala:225) ~[humio-assembly.jar:0.1]
	at com.humio.util.Timing$.time(Timing.scala:16) ~[humio-assembly.jar:0.1]
	at com.humio.util.Timing$.time(Timing.scala:10) ~[humio-assembly.jar:0.1]
	at com.humio.core.Context$.init(Context.scala:221) ~[humio-assembly.jar:0.1]
	at com.humio.core.Context$.apply(Context.scala:185) ~[humio-assembly.jar:0.1]
	at com.humio.core.Context$.apply(Context.scala:167) ~[humio-assembly.jar:0.1]
	at com.humio.main.ServerRunner$.main(ServerRunner.scala:85) ~[humio-assembly.jar:0.1]
	at com.humio.main.ServerRunner.main(ServerRunner.scala) ~[humio-assembly.jar:0.1]
```

**Comment by SaaldjorMike** [comment]
Hi @estahn. This repository is not longer being actively maintained, see the notice in the readme:

`This repo is no longer being actively maintained. Moving forward, we ask that you please report bugs and make and feature requests via our support desk at support@humio.com.`
